---
title: "Informe de Ventas"
output: html_document
---

Autor: Alejandro Ferrari - Fecha: 2025/08/09

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Carga de librerías necesarias
library(readxl)
library(ggplot2)
```

## Metodos de pago

Los datos, dejan ver a través de la gráfica que la _transferencia bancaria_ se viene imponiendo como  método electrónico preferido para el pago de nuestros productos.
```{r, echo=FALSE}
# Carga de la hoja BD, del archivo venta-cursos.xlsx
archivoi <- "venta-cursos.xlsx"
datosi <- read_excel(archivoi, sheet = "BD")
archivoii <- "venta-cursos.csv"
datosii <- read_excel(archivoi)

# control para ver si los archivos cargaron correctamente sus datos
#head(datosi)
#head(datosii)
```

```{r, echo=FALSE}
grafico_barras_i <- ggplot(
  data = datosi,
  aes(x = MétodoDePago, y = Valor)
) +
  geom_bar(
    stat = "identity",
    fill = "black"
  ) +
  labs(
    title = "Ventas Totales por Método de Pago",
    x = "Método de Pago",
    y = "Ventas en Euros"
  ) +
  theme_light()

# Mostrar el gráfico
print(grafico_barras_i)
```

